name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Deployment
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_URL }}
      SENDGRID_API_KEY: ${{ secrets.SUPABASE_URL }}
      EMAIL_BACKEND: ${{ secrets.SUPABASE_URL }}
      EMAIL_HOST: ${{ secrets.SUPABASE_URL }}
      EMAIL_PORT: ${{ secrets.SUPABASE_URL }}
      EMAIL_USE_TLS: ${{ secrets.SUPABASE_URL }}
      EMAIL_HOST_USER: ${{ secrets.SUPABASE_URL }}
      EMAIL_HOST_PASSWORD: ${{ secrets.SUPABASE_URL }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Deployment
    env:
      GO_LIVE: ${{ secrets.GO_LIVE }}
    steps:
      - name: Go Live!
        run: curl -X POST $GO_LIVE
